"""Agregar columna alerta_minima a repuesto

Revision ID: b159d3070da4
Revises: 
Create Date: 2026-04-01 15:40:35.489682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b159d3070da4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repuesto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alerta_minima', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repuesto', schema=None) as batch_op:
        batch_op.drop_column('alerta_minima')

    # ### end Alembic commands ###
